id: PD0BD00DE
initial_creation_type: input
source_metadata:
  Title: Śiṣyalekha
  Editor: I. Minaev
  Publisher: Oriental Institute
  Place of Publication: St. Petersburg
  Year: '1889'
  Śiṣyalekha:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:37:25.467410'
last_modified_at: '2022-03-08T16:37:25.467418'
